# ============================================
#         LabyRoyale - Configuration
#         PastequeWorld Network
# ============================================

general:
  prefix: "&6&l\u2726 &eLabyRoyale &6&l\u2726 &7\u00bb &f"
  # Nom du serveur hub dans la config BungeeCord
  hub-server: "hub"
  # Nom de CE serveur dans la config BungeeCord (pour ConnectOther)
  server-name: "labyroyale"

solo:
  min-players: 6
  max-players: 8
  maze-cells: 31
  preparation-time: 300
  pvp-time: 420
  storm-start-delay: 60
  storm-duration: 300
  countdown: 15
  wait-timeout: 60

duo:
  min-players: 8
  max-players: 16
  maze-cells: 40
  preparation-time: 360
  pvp-time: 480
  storm-start-delay: 60
  storm-duration: 360
  countdown: 15
  wait-timeout: 60

duel:
  min-players: 2
  max-players: 2
  maze-cells: 9
  preparation-time: 150
  pvp-time: 300
  storm-start-delay: 45
  storm-duration: 180
  countdown: 10
  wait-timeout: 30

maze:
  wall-height: 12
  base-y: 60
  special-rooms: 4
  ore-chance: 0.15
  bonus-chests: 6

lobby:
  y-level: 100
  size: 15

anti-cheat:
  fly-detection: true
  auto-kick: true
