name: LabyRoyale
version: 1.0.0
main: fr.pastequeworld.labyroyal.LabyRoyalPlugin
description: Mode de jeu LabyRoyale - Battle Royale en Labyrinthe pour PastequeWorld
author: PastequeWorld
commands:
  labyroyale:
    description: Commande principale du LabyRoyale
    aliases: [lr, laby]
    usage: /labyroyale <solo|duo|leave|admin>
